### ISSUE TITLE
[docs] Local font files

### ISSUE THREAD

**Issue by strarsis** [jonathantneal/postcss-font-magician#56]
Are there any examples on how to use font-magician with local font files (not on a foundry or API)?
Do I have to provide a base path? Does it autodiscover available formats?

**Comment by rajdee** [comment]
Hello @strarsis 
You can find an [example ](https://github.com/jonathantneal/postcss-font-magician#hosted)in the documentation

```js
fontMagician({
    hosted: ['./src/fonts', [/custom/path/to/fonts/on/site]]
})
```

The first argument of `hosted` option array is required and it should be a path that related to the project root. i.e. ./src/fonts In this case, the path to the fonts folder structure must match the structure of the path to the fonts folder on the server, because the path will be relative css file.

The second argument of `hosted` array is optional and it can be an arbitrary path which should match the fonts directory on the site. i.e. /assets/fonts
